name: Integration Tests Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive --remote
    - name: make
      run: make
    - name: Regular tests
      run: ./tests/test_regular.sh
      env:
        LC_ALL: C
    - name: Flag tests
      run: ./tests/test_flags.sh
      env:
        LC_ALL: C
    - name: Setuid, Setgid, Stickybi tests
      run: ./tests/test_usergroupid.sh
      env:
        LC_ALL: C
